FROM ubuntu:24.04

# Set environment variable to avoid interactive prompts during installation
ARG DEBIAN_FRONTEND=noninteractive

# Update the package list and install PostgreSQL and a client
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib && \
    rm -rf /var/lib/apt/lists/*

# Expose the default PostgreSQL port
EXPOSE 5432

COPY init.sql /docker-entrypoint-initdb.d/

# Set the default command to start the PostgreSQL server when the container runs
# This runs postgres in the foreground, which is typical for Docker containers
CMD ["postgres", "-D", "/var/lib/postgresql/data", "-c", "config_file=/etc/postgresql/postgresql.conf", "-c", "hba_file=/etc/postgresql/pg_hba.conf"]

RUN apt install -y redis-server

RUN  apt install -y python3 python3-pip python3-venv python3-dev \
build-essential libxml2-dev libxslt1-dev libffi-dev libpq-dev \
libssl-dev zlib1g-dev

